; blktiger_rtg_bezeldata.s -- indexed Black Tiger bezel backdrop (864x486).
; Generated by make_blktiger_rtg_bezel.py. 1 byte/pixel; the transparent
; playfield hole is index 0 and gets overdrawn by the game window.
        SECTION bezeldata,DATA
        XDEF    _blktiger_rtg_bezel
        XDEF    _blktiger_rtg_bezel_end
        CNOP 0,4
_blktiger_rtg_bezel:
        INCBIN  "blktiger_bezel_864x486.bin"
_blktiger_rtg_bezel_end:
