/* AUTO-GENERATED by make_blktiger_rtg_bezel.py -- do not edit. */
#ifndef BLKTIGER_RTG_BEZEL_H
#define BLKTIGER_RTG_BEZEL_H
#define BT_RTG_W  864
#define BT_RTG_H  486
#define BT_HOLE_X 116
#define BT_HOLE_Y 8
#define BT_HOLE_W 632
#define BT_HOLE_H 470
#define BT_GAME_X 163
#define BT_GAME_Y 8
#define BT_GAME_W 537
#define BT_GAME_H 470
#endif
