#!/usr/bin/env python3
"""Build the RTG-sized Black Tiger bezel backdrop from The Bezel Project overlay."""
from pathlib import Path
from PIL import Image

HERE = Path(__file__).resolve().parent
SRC = HERE.parent / "assets" / "blktiger_bezel.png"
OUT_BIN = HERE / "build" / "bezel" / "blktiger_bezel_864x486.bin"
OUT_H = HERE / "blktiger_rtg_bezel.h"

RTG_W, RTG_H = 864, 486
GAME_SRC_W, GAME_SRC_H = 256, 224
ALPHA_HOLE = 16


def rgb332(r, g, b):
    return ((r >> 5) << 5) | ((g >> 5) << 2) | (b >> 6)


def main():
    im = Image.open(SRC).convert("RGBA").resize((RTG_W, RTG_H), Image.Resampling.LANCZOS)
    px = im.load()

    minx, miny, maxx, maxy = RTG_W, RTG_H, -1, -1
    for y in range(RTG_H):
        for x in range(RTG_W):
            if px[x, y][3] < ALPHA_HOLE:
                minx = min(minx, x)
                miny = min(miny, y)
                maxx = max(maxx, x)
                maxy = max(maxy, y)
    if maxx < minx or maxy < miny:
        raise SystemExit(f"{SRC} has no transparent playfield hole")

    hole_x, hole_y = minx, miny
    hole_w, hole_h = maxx - minx + 1, maxy - miny + 1
    game_w = hole_w
    game_h = (GAME_SRC_H * game_w) // GAME_SRC_W
    if game_h > hole_h:
        game_h = hole_h
        game_w = (GAME_SRC_W * game_h) // GAME_SRC_H
    game_x = hole_x + (hole_w - game_w) // 2
    game_y = hole_y + (hole_h - game_h) // 2

    rgb = Image.new("RGB", (RTG_W, RTG_H), (0, 0, 0))
    rgb.paste(im, (0, 0), im)
    rpx = rgb.load()
    out = bytearray(RTG_W * RTG_H)
    for y in range(RTG_H):
        for x in range(RTG_W):
            out[y * RTG_W + x] = 0 if px[x, y][3] < ALPHA_HOLE else rgb332(*rpx[x, y])

    OUT_BIN.parent.mkdir(parents=True, exist_ok=True)
    OUT_BIN.write_bytes(out)
    OUT_H.write_text(
        "/* AUTO-GENERATED by make_blktiger_rtg_bezel.py -- do not edit. */\n"
        "#ifndef BLKTIGER_RTG_BEZEL_H\n"
        "#define BLKTIGER_RTG_BEZEL_H\n"
        f"#define BT_RTG_W  {RTG_W}\n"
        f"#define BT_RTG_H  {RTG_H}\n"
        f"#define BT_HOLE_X {hole_x}\n"
        f"#define BT_HOLE_Y {hole_y}\n"
        f"#define BT_HOLE_W {hole_w}\n"
        f"#define BT_HOLE_H {hole_h}\n"
        f"#define BT_GAME_X {game_x}\n"
        f"#define BT_GAME_Y {game_y}\n"
        f"#define BT_GAME_W {game_w}\n"
        f"#define BT_GAME_H {game_h}\n"
        "#endif\n"
    )
    print(f"  bezel {SRC.name} -> {OUT_BIN.name} ({len(out)} bytes RGB332)")
    print(f"  hole: x={hole_x} y={hole_y} w={hole_w} h={hole_h}")
    print(f"  game: x={game_x} y={game_y} w={game_w} h={game_h}")


if __name__ == "__main__":
    main()
