#!/usr/bin/env python3
"""Build the RTG-sized Side Arms bezel backdrop for the 864x486 indexed RTG presenter.

The presenter uses a fixed RGB332 palette for both game and bezel. That keeps the
8-bit RTG path fast without per-frame palette remapping or reserved bezel pens.

Source: The Bezel Project Side Arms overlay (1920x1080, transparent playfield hole).
Outputs:
  build/bezel/sidearms_bezel_864x486.bin   RGB332 indexed backdrop
  sidearms_rtg_bezel.h                      geometry
"""
from pathlib import Path
from PIL import Image

HERE = Path(__file__).resolve().parent
SRC = HERE.parent / "assets" / "sidearms_bezel.png"
OUT_BIN = HERE / "build" / "bezel" / "sidearms_bezel_864x486.bin"
OUT_H = HERE / "sidearms_rtg_bezel.h"

RTG_W, RTG_H = 864, 486          # 16:9, the RTG mode Ikari proved on this machine
ALPHA_HOLE = 16                  # alpha below this == transparent playfield

def rgb332(r, g, b):
    return ((r >> 5) << 5) | ((g >> 5) << 2) | (b >> 6)


def main():
    im = Image.open(SRC).convert("RGBA").resize((RTG_W, RTG_H), Image.Resampling.LANCZOS)
    px = im.load()

    # --- locate the transparent playfield hole (where the game is drawn) ---
    minx, miny, maxx, maxy = RTG_W, RTG_H, -1, -1
    for y in range(RTG_H):
        for x in range(RTG_W):
            if px[x, y][3] < ALPHA_HOLE:
                if x < minx: minx = x
                if x > maxx: maxx = x
                if y < miny: miny = y
                if y > maxy: maxy = y
    gx, gy = minx, miny
    gw, gh = (maxx - minx + 1), (maxy - miny + 1)

    # --- composite over black, convert non-hole art into the fixed RGB332 palette ---
    rgb = Image.new("RGB", (RTG_W, RTG_H), (0, 0, 0))
    rgb.paste(im, (0, 0), im)
    rpx = rgb.load()
    out = bytearray(RTG_W * RTG_H)
    for y in range(RTG_H):
        for x in range(RTG_W):
            out[y * RTG_W + x] = 0 if px[x, y][3] < ALPHA_HOLE else rgb332(*rpx[x, y])
    OUT_BIN.parent.mkdir(parents=True, exist_ok=True)
    OUT_BIN.write_bytes(out)

    OUT_H.write_text(
        "/* AUTO-GENERATED by make_sidearms_rtg_bezel.py -- do not edit. */\n"
        "#ifndef SIDEARMS_RTG_BEZEL_H\n"
        "#define SIDEARMS_RTG_BEZEL_H\n"
        f"#define SA_RTG_W  {RTG_W}\n"
        f"#define SA_RTG_H  {RTG_H}\n"
        f"#define SA_GAME_X {gx}\n"
        f"#define SA_GAME_Y {gy}\n"
        f"#define SA_GAME_W {gw}\n"
        f"#define SA_GAME_H {gh}\n"
        "#endif\n"
    )
    print(f"  bezel {SRC.name} -> {OUT_BIN.name} ({RTG_W*RTG_H} bytes RGB332)")
    print(f"  hole/game window: x={gx} y={gy} w={gw} h={gh} (aspect {gw/gh:.3f})")


if __name__ == "__main__":
    main()
