/* AUTO-GENERATED by make_sidearms_rtg_bezel.py -- do not edit. */
#ifndef SIDEARMS_RTG_BEZEL_H
#define SIDEARMS_RTG_BEZEL_H
#define SA_RTG_W  864
#define SA_RTG_H  486
#define SA_GAME_X 116
#define SA_GAME_Y 8
#define SA_GAME_W 632
#define SA_GAME_H 470
#endif
