; sidearms_rtg_bezeldata.s -- indexed Side Arms bezel backdrop (864x486).
; Generated by make_sidearms_rtg_bezel.py. 1 byte/pixel; the transparent
; playfield hole is zero (the game overwrites it).
        XDEF    _sidearms_rtg_bezel
        XDEF    _sidearms_rtg_bezel_end

        SECTION data,DATA
_sidearms_rtg_bezel:
        incbin  "sidearms_bezel_864x486.bin"
_sidearms_rtg_bezel_end:
