/* src/hal/hal_io.c
 * ============================================================
 *  I/O dispatch layer -- the bridge between the 6809/Z80
 *  interpreter cores and the 68k Amiga HAL.
 * ============================================================
 *
 * How it works:
 *   1. At startup, hal_io_init() reads the game's io_map.json
 *      (compiled in as a C array, generated by the python tool)
 *      and builds a 256-entry LUT keyed by the LOW 8 BITS of the
 *      arcade I/O address. Each entry is either NULL (passthrough
 *      to the underlying memory) or a pointer to a handler.
 *   2. The 6809 emulator is given hal_io_read / hal_io_write as
 *      its read/write callbacks (replacing the raw memory access
 *      that would normally hit our 64k address space).
 *   3. When the 6809 does LDA $7800, the emulator calls
 *      hal_io_read(cpu, 0x7800). The LUT lookup fires
 *      hal_watchdog_kick() which is a real 68k function in
 *      handlers.s that touches the Amiga hardware.
 *
 * Why low 8 bits: most Namco arcade I/O chips decode on the low
 * 8 bits (the chip-enable line is a higher address bit). The
 * 256-entry table covers all the I/O space without needing a
 * full 64k mapping.
 *
 * This file is C so it can be compiled by m68k-amigaos-gcc. It
 * declares NO Amiga-specific types -- only the handler functions
 * (which live in handlers.s) and the LUT entries.
 */
#include <stdint.h>
#include <stdbool.h>

/* Forward declare the 6809 cpu type to keep this header
 * decoupled from mc6809.h (so we can compile this file
 * standalone for the host smoke test). */
struct mc6809;
typedef uint8_t  mc6809byte__t;
typedef uint16_t mc6809addr__t;
typedef mc6809byte__t (*mc6809_read_func)(struct mc6809 *, mc6809addr__t, bool);

/* ============================================================
 *  Handler function table
 * ============================================================
 * Each handler is called when the 6809 hits a specific I/O
 * address. The handler does the actual Amiga-side work
 * (set palette, kick watchdog, swap copper list, etc).
 *
 * Handlers live in src/hal/handlers.s (assembled with vasm).
 * They're declared with C linkage here.
 *
 * For an I/O READ, the handler returns a byte.
 * For an I/O WRITE, the handler receives the byte to write.
 * The kind flag tells us which.
 */
typedef enum {
    HAL_IO_READ  = 0,
    HAL_IO_WRITE = 1,
} hal_io_dir_t;

typedef uint8_t (*hal_io_read_handler_t)(mc6809addr__t addr);
typedef void    (*hal_io_write_handler_t)(mc6809addr__t addr, uint8_t val);

/* Single handler entry in the LUT. One handler can do both
 * read and write (most Namco I/O chips do), or just one. */
typedef struct {
    const char        *name;       /* for logging, e.g. "watchdog_kick" */
    hal_io_read_handler_t  read;
    hal_io_write_handler_t write;
} hal_io_handler_t;

/* ============================================================
 *  LUT -- 256 entries, indexed by low 8 bits of arcade address
 * ============================================================
 * NULL entry = no handler, pass through to underlying memory.
 * Generated at build time by namco_amiga.tools.generate_dispatch
 * from games/<name>/io_map.json. We declare it extern here.
 */
extern const hal_io_handler_t *hal_io_lut[256];

/* ============================================================
 *  Public API
 * ============================================================
 */

/* Initialise the dispatch table. Called once at startup from
 * amiga_main. */
void hal_io_init(void);

/* 6809 read callback. Replaces cpu->read in the emulator. */
mc6809byte__t hal_io_read(struct mc6809 *cpu, mc6809addr__t addr, bool debug_fetch);

/* 6809 write callback. Replaces cpu->write in the emulator. */
void hal_io_write(struct mc6809 *cpu, mc6809addr__t addr, mc6809byte__t val);

/* Z80 I/O callbacks. These are the symbols the z80 core
 * already calls (_in_impl, _out_impl). They go through the
 * same LUT but with a separate 256-entry table for the z80
 * I/O space (which is also address-keyed). */
uint8_t _in_impl(uint16_t addr);
void    _out_impl(uint16_t addr, uint8_t val);
