/* AUTO-GENERATED by make_commando_rtg_bezel.py -- do not edit. */
#ifndef COMMANDO_RTG_BEZEL_H
#define COMMANDO_RTG_BEZEL_H
#define CMD_RTG_W  864
#define CMD_RTG_H  486
#define CMD_GAME_X 248
#define CMD_GAME_Y 33
#define CMD_GAME_W 367
#define CMD_GAME_H 419
#endif
