#!/usr/bin/env python3
from pathlib import Path
from PIL import Image

HERE = Path(__file__).resolve().parent
SRC = HERE.parent / "assets" / "commando_bezel.png"
OUT_BIN = HERE / "build" / "bezel" / "commando_bezel_864x486.bin"
OUT_H = HERE / "commando_rtg_bezel.h"

RTG_W, RTG_H = 864, 486
GAME_ASPECT = 224 / 256
ALPHA_HOLE = 16

def rgb332(r, g, b):
    return ((r >> 5) << 5) | ((g >> 5) << 2) | (b >> 6)

def main():
    im = Image.open(SRC).convert("RGBA").resize((RTG_W, RTG_H), Image.Resampling.LANCZOS)
    px = im.load()
    minx, miny, maxx, maxy = RTG_W, RTG_H, -1, -1
    for y in range(RTG_H):
        for x in range(RTG_W):
            if px[x, y][3] < ALPHA_HOLE:
                minx = min(minx, x); miny = min(miny, y)
                maxx = max(maxx, x); maxy = max(maxy, y)

    if maxx < minx:
        hole_x, hole_y, hole_w, hole_h = 320, 18, 224, 450
    else:
        hole_x, hole_y = minx, miny
        hole_w, hole_h = maxx - minx + 1, maxy - miny + 1

    if hole_w / hole_h > GAME_ASPECT:
        gh = hole_h
        gw = int(round(gh * GAME_ASPECT))
    else:
        gw = hole_w
        gh = int(round(gw / GAME_ASPECT))
    gx = hole_x + (hole_w - gw) // 2
    gy = hole_y + (hole_h - gh) // 2

    rgb = Image.new("RGB", (RTG_W, RTG_H), (0, 0, 0))
    rgb.paste(im, (0, 0), im)
    rpx = rgb.load()
    out = bytearray(RTG_W * RTG_H)
    for y in range(RTG_H):
        for x in range(RTG_W):
            in_game = gx <= x < gx + gw and gy <= y < gy + gh
            out[y * RTG_W + x] = 0 if in_game else rgb332(*rpx[x, y])
    OUT_BIN.parent.mkdir(parents=True, exist_ok=True)
    OUT_BIN.write_bytes(out)
    OUT_H.write_text(
        "/* AUTO-GENERATED by make_commando_rtg_bezel.py -- do not edit. */\n"
        "#ifndef COMMANDO_RTG_BEZEL_H\n"
        "#define COMMANDO_RTG_BEZEL_H\n"
        f"#define CMD_RTG_W  {RTG_W}\n"
        f"#define CMD_RTG_H  {RTG_H}\n"
        f"#define CMD_GAME_X {gx}\n"
        f"#define CMD_GAME_Y {gy}\n"
        f"#define CMD_GAME_W {gw}\n"
        f"#define CMD_GAME_H {gh}\n"
        "#endif\n"
    )
    print(f"bezel -> {OUT_BIN.name}; game x={gx} y={gy} w={gw} h={gh}")

if __name__ == "__main__":
    main()
